// Curated taxonomies extracted from wetten.overheid.nl "Uitgebreid zoeken" form.
// Source: Examples/Uitgebreid zoeken - Overheid.nl _ Wetten.nl.htm
// Codes (lowercase short codes) appear in the HTML as the <input value="..."> attribute;
// the data-value attribute holds the Dutch display label that is sent to the backend.
// Labels here are the full user-facing strings.

export const MINISTERIES: ReadonlyArray<readonly [code: string, label: string]> = [
  ["az", "Algemene Zaken"],
  ["aenm", "Asiel en Migratie"],
  ["bzk", "Binnenlandse Zaken en Koninkrijksrelaties"],
  ["buza", "Buitenlandse Zaken"],
  ["def", "Defensie"],
  ["ez", "Economische Zaken"],
  ["ezk", "Economische Zaken en Klimaat"],
  ["fin", "Financiën"],
  ["im", "Infrastructuur en Milieu"],
  ["iw", "Infrastructuur en Waterstaat"],
  ["jv", "Justitie en Veiligheid"],
  ["kgg", "Klimaat en Groene Groei"],
  ["lnv", "Landbouw, Natuur en Voedselkwaliteit"],
  ["lvvn", "Landbouw, Visserij, Voedselzekerheid en Natuur"],
  ["ocw", "Onderwijs, Cultuur en Wetenschap"],
  ["szw", "Sociale Zaken en Werkgelegenheid"],
  ["vj", "Veiligheid en Justitie"],
  ["vws", "Volksgezondheid, Welzijn en Sport"],
  ["vro", "Volkshuisvesting en Ruimtelijke Ordening"],
];

export const ZBOS: ReadonlyArray<readonly [code: string, label: string]> = [
  ["acm", "Autoriteit Consument en Markt"],
  ["afm", "Autoriteit Financiële Markten"],
  ["anvs", "Autoriteit Nucleaire Veiligheid en Stralingsbescherming"],
  ["ap", "Autoriteit Persoonsgegevens"],
  ["bar", "Bureau Architectenregister"],
  ["bft", "Bureau Financieel Toezicht"],
  ["cak", "CAK"],
  ["cevo", "CEVO"],
  ["cbr", "Centraal Bureau Rijvaardigheidsbewijzen"],
  ["cbs", "Centraal Bureau voor de Statistiek - Directeur-Generaal van de Statistiek"],
  ["coa", "Centraal Orgaan opvang Asielzoekers"],
  ["ccd", "Centrale Commissie Dierproeven"],
  ["ccmo", "Centrale Commissie Mensgebonden Onderzoek"],
  ["cwi", "Centrale Organisatie Werk en Inkomen"],
  ["ciz", "Centrum Indicatiestelling Zorg"],
  ["cgd", "College Gerechtelijk deskundigen"],
  ["cszi", "College Sanering Ziekenhuisvoorzieningen"],
  ["cszo", "College sanering zorginstellingen"],
  ["cbg", "College ter Beoordeling van Geneesmiddelen"],
  ["cvta", "College van toezicht collectieve beheersorganisaties auteurs- en naburige rechten"],
  ["ctz", "College van toezicht op de zorgverzekeringen"],
  ["cve", "College voor Examens"],
  ["cte", "College voor Toetsen en Examens"],
  ["ctgb", "College voor de toelating van gewasbeschermingmiddelen en biociden"],
  ["cvdm", "Commissariaat voor de Media"],
  ["cea", "Commissie Eindtermen Accountantsopleiding"],
  ["csgm", "Commissie schadefonds geweldsmisdrijven"],
  ["dnb", "De Nederlandsche Bank N.V."],
  ["duo", "Dienst Uitvoering Onderwijs"],
  ["rdw", "Dienst Wegverkeer"],
  ["da", "Dopingautoriteit"],
  ["ff", "Faunafonds"],
  ["kbbi", "Fundeon KBBI"],
  ["hc", "Huurcommissie"],
  ["inno", "Innovam"],
  ["kds", "Kadaster"],
  ["kvk", "Kamer van Koophandel"],
  ["kvb", "Kamer voor de Binnenvisserij"],
  ["ksa", "Kansspelautoriteit"],
  ["kch", "Kenniscentrum Handel"],
  ["kr", "Kiesraad"],
  ["kb", "Koninklijke Bibliotheek"],
  ["ecabo", "Landelijk Orgaan Economische & Administratieve Beroepscategorieën"],
  ["lvnl", "Luchtverkeersleiding Nederland"],
  ["mf", "Mondriaan Fonds"],
  ["nvao", "Nederlands-Vlaamse Accreditatieorganisatie hoger onderwijs"],
  ["nwo", "Nederlandse Organisatie voor Wetenschappelijk Onderzoek"],
  ["tno", "Nederlandse Organisatie voor toegepast-natuurwetenschappelijk onderzoek"],
  ["npo", "Nederlandse Publieke Omroep"],
  ["nza", "Nederlandse Zorgautoriteit"],
  ["nea", "Nederlandse emissieautoriteit"],
  ["ovv", "Onderzoeksraad voor veiligheid"],
  ["pur", "Pensioen- en Uitkeringsraad"],
  ["pol", "Politieacademie"],
  ["ruwv", "Raad van bestuur UWV"],
  ["ra", "Raad voor Accreditatie"],
  ["rp", "Raad voor plantenrassen"],
  ["rvr", "Raad voor Rechtsbijstand"],
  ["rrh", "Raad voor Rechtsbijstand 's-Hertogenbosch"],
  ["rc", "Referendumcommissie"],
  ["rgs", "Registratiecommissies KNMG, KNMP, KNMT, FGzPt en VenVN"],
  ["rhm", "Rijkshavenmeesters"],
  ["svb", "Sociale Verzekeringsbank"],
  ["sbb", "Staatsbosbeheer"],
  ["sg", "Staten-Generaal"],
  ["bkd", "Stichting Bloembollenkeuringsdienst"],
  ["cokz", "Stichting Centraal Orgaan voor Kwaliteitsaangelegenheden in de Zuivel"],
  ["cpe", "Stichting Controlebureau voor Pluimvee, Eieren en Eiproducten"],
  ["sdkb", "Stichting Donorgegevens Kunstmatige Bevruchting"],
  ["sfc", "Stichting Fonds voor Cultuurparticipatie"],
  ["bkvb", "Stichting Fonds voor beeldende kunsten, vormgeving en bouwkunst"],
  ["sfl", "Stichting Fonds voor de Letteren"],
  ["fst", "Stichting Fonds voor de Scheppende Toonkunst"],
  ["shm", "Stichting Hout & Meubel"],
  ["kbb", "Stichting Kenniscentrum Beroepsonderwijs Bedrijfsleven PMLF"],
  ["kcb", "Stichting Kwaliteits-Controle-Bureau"],
  ["niwo", "Stichting Nationale en Internationale Wegvervoer Organisatie"],
  ["nff", "Stichting Nederlands Fonds voor de Film"],
  ["snfp", "Stichting Nederlands Fonds voor Podiumkunsten"],
  ["snl", "Stichting Nederlands Letterenfonds"],
  ["snlpv", "Stichting Nederlands Literair Productie- en Vertalingenfonds"],
  ["nakz", "Stichting Nederlandse Algemene Keuringsdienst voor zaaizaad en pootgoed van landbouwgewassen"],
  ["nakt", "Stichting Nederlandse Algemene Kwaliteitsdienst voor de Tuinbouw"],
  ["spo", "Stichting Participatiefonds voor het Onderwijs"],
  ["pvk", "Stichting Pensioen- & Verzekeringskamer"],
  ["ssbb", "Stichting Samenwerking Beroepsonderwijs en Bedrijfsleven"],
  ["skal", "Stichting Skal"],
  ["ssci", "Stichting Stimuleringsfonds Creatieve Industrie"],
  ["vf", "Stichting Vervangingsfonds en Bedrijfsgezondheidszorg voor het Onderwijs"],
  ["sncm", "Stimuleringsfonds Nederlandse culturele mediaproducties"],
  ["sj", "Stimuleringsfonds voor de Journalistiek"],
  ["uwv", "Uitvoeringsinstituut werknemersverzekeringen"],
  ["vi", "Vereveningsinstantie"],
  ["vp", "Verispect BV"],
  ["vutf", "Vut-fonds"],
  ["wi", "Waarborginstellingen"],
  ["zr", "Ziekenfondsraad"],
  ["zn", "Zorginstituut Nederland"],
  ["zonmw", "ZorgOnderzoek Nederland / Medische Wetenschappen"],
];

export const PBOS: ReadonlyArray<readonly [code: string, label: string]> = [
  ["ba", "Bedrijfschap Afbouw"],
  ["hor", "Bedrijfschap Horeca en Catering"],
  ["bnb", "Bedrijfschap voor het Natuursteenbedrijf (Opgeheven)"],
  ["bsb", "Bedrijfschap voor het Slagersbedrijf (Opgeheven)"],
  ["bos", "Bosschap"],
  ["hbag", "Hoofdbedrijfschap Agrarische Groothandel"],
  ["hba", "Hoofdbedrijfschap Ambachten"],
  ["hbd", "Hoofdbedrijfschap Detailhandel"],
  ["hpa", "Hoofdproductschap Akkerbouw"],
  ["kbob", "Kenniscentra beroepsonderwijs bedrijfsleven"],
  ["nivra", "Koninklijk Nederlands Instituut van Registeraccountants"],
  ["kbvg", "Koninklijke Beroepsorganisatie van Gerechtsdeurwaarders"],
  ["knb", "Koninklijke Notariële Beroepsorganisatie"],
  ["nlc", "Nederlandse Loodsencorporatie"],
  ["novaa", "Nederlandse Orde van Accountants-Administratieconsulenten"],
  ["nova", "Nederlandse Orde van Advocaten"],
  ["nba", "Nederlandse beroepsorganisatie van accountants"],
  ["pa", "Productschap Akkerbouw"],
  ["pdv", "Productschap Diervoeder"],
  ["pd", "Productschap Dranken"],
  ["gzp", "Productschap Granen, Zaden en Peulvruchten"],
  ["ppe", "Productschap Pluimvee en Eieren"],
  ["pt", "Productschap Tuinbouw"],
  ["pvv", "Productschap Vee en Vlees"],
  ["pv", "Productschap Vis"],
  ["pw", "Productschap Wijn"],
  ["pz", "Productschap Zuivel"],
  ["mvo", "Productschap voor Margarine, Vetten en Oliën"],
  ["ser", "Sociaal-Economische Raad"],
];

// Note on Overheidsdomein: the HTML `value` attribute (the short code) is what goes on the
// wire as the URL param, but the `data-value` (full Dutch phrase) is the canonical label
// stored in the taxonomy. Both are preserved here as code → label.
export const OVERHEIDSDOMEINEN: ReadonlyArray<readonly [code: string, label: string]> = [
  ["bel", "Belastingen"],
  ["bwl", "Bouwen, wonen en leefomgeving"],
  ["csvt", "Cultuur, sport, vrije tijd"],
  ["def", "Defensie"],
  ["eo", "Economie en ondernemen"],
  ["fjg", "Familie, jeugd en gezin"],
  ["fin", "Financiën"],
  ["gz", "Gezondheid en zorg"],
  ["iii", "Immigratie, integratie en inburgering"],
  ["ios", "Internationale- en ontwikkelingssamenwerking"],
  ["lnv", "Landbouw, natuur en voedsel"],
  ["mrw", "Milieu, ruimte en water"],
  ["ow", "Onderwijs en wetenschap"],
  ["oov", "Openbare orde en veiligheid"],
  ["obk", "Overheid, bestuur en koninkrijk"],
  ["rec", "Rechtspraak"],
  ["sut", "Subsidies, uitkeringen en toeslagen"],
  ["vv", "Verkeer en vervoer"],
  ["wlb", "Werk- en loopbaan"],
];

// Rechtsgebieden — hoofdgebieden hold parent = null, subgebieden hold the hoofdgebied code.
// "Hoofdgebied" rows that have NO subgebieden are still emitted with parent = null so they
// can be selected directly.
export const RECHTSGEBIEDEN: ReadonlyArray<{ code: string; label: string; parent: string | null }> = [
  { code: "argr", label: "Agrarisch recht", parent: null },

  { code: "arszr", label: "Arbeidsrecht en sociaal-zekerheidsrecht", parent: null },
  { code: "ambr", label: "Ambtenarenrecht", parent: "arszr" },
  { code: "arbr", label: "Arbeidsrecht", parent: "arszr" },
  { code: "mambr", label: "Militaire ambtenarenrecht", parent: "arszr" },
  { code: "penr", label: "Pensioenrecht", parent: "arszr" },
  { code: "szr", label: "Sociaal zekerheidsrecht", parent: "arszr" },

  { code: "arbi", label: "Arbitrage", parent: null },

  { code: "berf", label: "Bank- en effectenrecht, financiering", parent: null },
  { code: "bar", label: "Bankrecht", parent: "berf" },
  { code: "efr", label: "Effectenrecht", parent: "berf" },
  { code: "fz", label: "Financiering en zekerheden", parent: "berf" },
  { code: "tbkw", label: "Toezicht bank- en kredietwezen", parent: "berf" },

  { code: "ber", label: "Belastingrecht", parent: null },
  { code: "btwa", label: "BTW en accijns", parent: "ber" },
  { code: "db", label: "Dividendbelasting", parent: "ber" },
  { code: "fbr", label: "Formeel belastingrecht", parent: "ber" },
  { code: "hlo", label: "Heffingen lokale overheden", parent: "ber" },
  { code: "ib", label: "Inkomstenbelasting", parent: "ber" },
  { code: "intr", label: "Internationale regelingen", parent: "ber" },
  { code: "id", label: "Invoer en douane", parent: "ber" },
  { code: "invr", label: "Invorderingsrecht", parent: "ber" },
  { code: "lp", label: "Loonbelasting en premieheffing", parent: "ber" },
  { code: "mb", label: "Milieubelasting", parent: "ber" },
  { code: "ssr", label: "Successie- en schenkingsrecht", parent: "ber" },
  { code: "vbr", label: "Vennootschapsbelastingrecht", parent: "ber" },

  { code: "csa", label: "Contracten, schade en aansprakelijkheid", parent: null },
  { code: "aanr", label: "Aansprakelijkheidsrecht", parent: "csa" },
  { code: "conr", label: "Consumentenrecht", parent: "csa" },
  { code: "icr", label: "Internationaal contractrecht", parent: "csa" },
  { code: "verbr", label: "Verbintenissenrecht", parent: "csa" },
  { code: "verzr", label: "Verzekeringsrecht", parent: "csa" },

  { code: "culr", label: "Cultureel recht", parent: null },
  { code: "fer", label: "Financieel en economisch recht", parent: null },
  { code: "grfr", label: "Gezondheidsrecht en farmaceutisch recht", parent: null },

  { code: "gr", label: "Goederenrecht", parent: null },
  { code: "eigr", label: "Eigendomsrecht", parent: "gr" },
  { code: "ev", label: "Erfpacht, vruchtgebruik", parent: "gr" },
  { code: "hrpr", label: "Hypotheekrecht en pandrecht (zekerheidsrechten)", parent: "gr" },

  { code: "infr", label: "Informatierecht", parent: null },
  { code: "ictr", label: "ICT-recht", parent: "infr" },
  { code: "telr", label: "Telecomrecht", parent: "infr" },

  { code: "insr", label: "Insolventierecht", parent: null },
  { code: "fa", label: "Faillissement", parent: "insr" },
  { code: "schs", label: "Schuldsanering", parent: "insr" },
  { code: "surs", label: "Surseance", parent: "insr" },

  { code: "ie", label: "Intellectuele eigendom", parent: null },
  { code: "ar", label: "Auteursrecht", parent: "ie" },
  { code: "ier", label: "Intellectueel eigendomsrecht", parent: "ie" },
  { code: "octr", label: "Octrooirecht", parent: "ie" },

  { code: "ipriipr", label: "Internationaal privaatrecht Inclusief internationaal procesrecht", parent: null },

  { code: "ipr", label: "Internationaal publiekrecht", parent: null },
  { code: "menr", label: "Mensenrechten", parent: "ipr" },
  { code: "os", label: "Ontwikkelingssamenwerking", parent: "ipr" },
  { code: "vr", label: "Volkenrecht", parent: "ipr" },

  { code: "lr", label: "Levensmiddelenrecht", parent: null },
  { code: "medr", label: "Mededingingsrecht", parent: null },

  { code: "migr", label: "Migratierecht", parent: null },
  { code: "nr", label: "Nationaliteitsrecht", parent: "migr" },
  { code: "vreer", label: "Vreemdelingenrecht", parent: "migr" },

  { code: "op", label: "Ondernemingspraktijk", parent: null },
  { code: "fo", label: "Fusies en overnames", parent: "op" },
  { code: "onr", label: "Ondernemingsrecht", parent: "op" },
  { code: "sv", label: "Stichtingen en verenigingen", parent: "op" },
  { code: "venr", label: "Vennootschapsrecht", parent: "op" },

  { code: "ondr", label: "Onderwijsrecht", parent: null },
  { code: "oovr", label: "Openbare orde en veiligheidsrecht", parent: null },

  { code: "pfr", label: "Personen- en familierecht", parent: null },
  { code: "es", label: "Echtscheiding", parent: "pfr" },
  { code: "erfr", label: "Erfrecht", parent: "pfr" },
  { code: "fr", label: "Familierecht", parent: "pfr" },
  { code: "jr", label: "Jeugdrecht (m.u.v. jeugdstrafrecht)", parent: "pfr" },
  { code: "perr", label: "Personenrecht", parent: "pfr" },

  { code: "pri", label: "Privacy", parent: null },

  { code: "pror", label: "Procesrecht", parent: null },
  { code: "bepr", label: "Bestuursprocesrecht", parent: "pror" },
  { code: "bupr", label: "Burgerlijk procesrecht", parent: "pror" },
  { code: "strpr", label: "Strafprocesrecht", parent: "pror" },

  { code: "rom", label: "Ruimtelijke ordening en milieu", parent: null },
  { code: "milr", label: "Milieurecht", parent: "rom" },
  { code: "ogr", label: "Omgevingsrecht", parent: "rom" },
  { code: "wr", label: "Waterrecht", parent: "rom" },

  { code: "spr", label: "Sportrecht", parent: null },

  { code: "sbr", label: "Staats- en bestuursrecht", parent: null },
  { code: "br", label: "Bestuursrecht", parent: "sbr" },
  { code: "mtr", label: "Militair recht", parent: "sbr" },
  { code: "star", label: "Staatsrecht", parent: "sbr" },

  { code: "strr", label: "Strafrecht", parent: null },
  { code: "fsr", label: "Financieel-economisch strafrecht", parent: "strr" },
  { code: "isr", label: "Internationaal strafrecht", parent: "strr" },
  { code: "jsr", label: "Jeugdstrafrecht", parent: "strr" },
  { code: "msr", label: "Milieustrafrecht", parent: "strr" },
  { code: "ptr", label: "Penitentiair recht", parent: "strr" },
  { code: "sr", label: "Strafrecht (algemeen)", parent: "strr" },
  { code: "vkr", label: "Verkeersrecht", parent: "strr" },

  { code: "tr", label: "Tuchtrecht", parent: null },
  { code: "vvr", label: "Vervoersrecht", parent: null },

  { code: "wogbr", label: "Wonen, onroerend goed, bouwrecht", parent: null },
  { code: "bor", label: "Bouwrecht", parent: "wogbr" },
  { code: "hr", label: "Huurrecht", parent: "wogbr" },
  { code: "ongr", label: "Onroerend goedrecht", parent: "wogbr" },
];

// Thema's verdragen (Select_Taxonomie)
export const VERDRAG_THEMAS: ReadonlyArray<readonly [code: string, label: string]> = [
  ["arbe", "Arbeid"],
  ["arbi", "Arbitrage"],
  ["bel", "Belasting"],
  ["bpr", "Burgerlijk Procesrecht"],
  ["bs", "Burgerlijke stand"],
  ["cul", "Cultuur"],
  ["dcb", "Diplomatieke en consulaire betrekkingen"],
  ["dou", "Douane"],
  ["es", "Economische samenwerking"],
  ["eii", "Eigendom, intellectuele en industriële"],
  ["ene", "Energie"],
  ["ff", "Flora en Fauna"],
  ["gi", "Gerechtshoven, Internationale"],
  ["gr", "Geschillenregeling"],
  ["gez", "Gezondheid"],
  ["gre", "Grenzen"],
  ["gro", "Grondstoffen"],
  ["io", "Instellingen en organisaties"],
  ["inv", "Investeringen"],
  ["lv", "Landbouw en visserij"],
  ["luc", "Luchtvaart"],
  ["mr", "Mensenrechten"],
  ["mil", "Milieu"],
  ["mt", "Militair"],
  ["mon", "Monetair"],
  ["nat", "Nationaliteit"],
  ["ns", "Nucleaire samenwerking"],
  ["ond", "Onderwijs"],
  ["os", "Ontwikkelingssamenwerking"],
  ["ovp", "Overname van personen"],
  ["pfr", "Personen- en Familierecht"],
  ["pm", "Personenverkeer en migratie"],
  ["post", "Post"],
  ["pr", "Privaatrecht"],
  ["pi", "Privileges en immuniteiten"],
  ["rh", "Rechtshulp"],
  ["rui", "Ruimte"],
  ["sv", "Scheepvaart"],
  ["sz", "Sociale Zekerheid"],
  ["sw", "Spoorwegen"],
  ["sr", "Strafrecht"],
  ["ts", "Technische samenwerking"],
  ["tc", "Telecommunicatie"],
  ["ter", "Terrorisme"],
  ["toe", "Toerisme"],
  ["ul", "Uitlevering"],
  ["vm", "Verdovende middelen"],
  ["vr", "Verdragenrecht"],
  ["ver", "Vervoer"],
  ["vrd", "Visa en reisdocumenten"],
  ["vlu", "Vluchtelingen"],
  ["vvv", "Voortzetting van verdragen"],
  ["vre", "Vrede"],
  ["vv", "Vriendschapsverdrag"],
  ["wap", "Wapens"],
  ["wat", "Water"],
  ["wv", "Wegverkeer"],
  ["ws", "Wetenschappelijke samenwerking"],
  ["zv", "Zetelverdrag"],
];

// Zoek in onderdelen (Select_OND) — values are numeric strings as sent over the wire.
export const ONDERDELEN: ReadonlyArray<readonly [code: string, label: string]> = [
  ["2", "Opschriften binnen het lichaam van de regeling"],
  ["3", "Artikelen of daarmee vergelijkbare tekst"],
  ["5", "Bijlagen"],
  ["6", "Officiële inhoudsopgave"],
];

// Datumbereik (<select name="ZoekOp_Datumbereik">)
export const DATUMBEREIK: ReadonlyArray<readonly [code: string, label: string]> = [
  ["1", "Voor"],
  ["2", "Na"],
  ["3", "Tussen"],
  ["4", "Op"],
];

// Gepubliceerd in (<select name="ZoekOp_BronPublicatie">) — empty value omitted.
export const BRON_PUBLICATIE: ReadonlyArray<readonly [code: string, label: string]> = [
  ["Stb", "Staatsblad"],
  ["Stcrt", "Staatscourant"],
  ["Supplement-Stcrt", "Staatscourant-supplement"],
  ["Trb", "Tractatenblad"],
  ["Uitleg", "Uitleg"],
  ["Infob", "Infobulletin"],
  ["Vbbo", "PBO blad"],
];

// Datumtype radios (ZoekOp_DatumtypeInwerkingtreding). "Totstandkoming" is disabled in
// the HTML for non-verdragen searches, but is included here as it is a valid value
// when searching verdragen.
export const DATUMTYPE: ReadonlyArray<readonly [code: string, label: string]> = [
  ["Inwerkingtreding", "Inwerkingtreding"],
  ["Ondertekening", "Ondertekening"],
  ["Totstandkoming", "Totstandkoming"],
];

// Datumscope radios (ZoekOp_DatumscopeRegeling).
export const DATUMSCOPE: ReadonlyArray<readonly [code: string, label: string]> = [
  ["Regeling", "Regeling"],
  ["Artikel", "Artikel"],
];
